# Generated by Django 3.2.3 on 2021-06-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_legaldoc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldoc',
            options={'ordering': ['-up_date']},
        ),
    ]
