# Generated by Django 3.2.3 on 2021-06-14 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_legaldoc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldoc',
            name='doc',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'img'])]),
        ),
    ]
