# Generated by Django 3.2.3 on 2021-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldoc',
            name='tag',
            field=models.ManyToManyField(related_name='legaldocs', to='documents.Tag'),
        ),
    ]
