# Generated by Django 3.2.3 on 2021-06-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20210608_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldoc',
            options={'ordering': ['id']},
        ),
    ]
